services:
  - type: web
    name: job-portal
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate --noinput
      python manage.py collectstatic --noinput
    startCommand: gunicorn job1.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
